### ISSUE TITLE
Roadmap for v1.0.0

### ISSUE THREAD

**Issue by petk** [php-earth/docker-php#1]
For the stable release of `v1.0.0` the following tasks need to be done:

* Add support for the following extensions:
  * [ ] [Apache](http://php.net/manual/en/book.apache.php)
  * [x] [COM](http://php.net/manual/en/book.com.php)
  * [x] [DBA](http://php.net/manual/en/book.dba.php)
  * [ ] [Firebird/Interbase](http://php.net/manual/en/book.ibase.php)
  * [x] [GMP](http://php.net/manual/en/book.gmp.php)
  * [x] [imagick](https://pecl.php.net/package/imagick)
  * [x] [Informix](http://php.net/manual/en/book.ifx.php)
  * [x] [IMAP](http://php.net/manual/en/book.imap.php)
  * [x] [Frontbase](http://php.net/manual/en/book.fbsql.php)
  * [x] [msql](http://php.net/manual/en/book.msql.php)
  * [x] [LDAP](http://php.net/manual/en/book.ldap.php)
  * [x] [NSAPI](http://php.net/manual/en/book.nsapi.php)
  * [ ] [OCI8](http://php.net/manual/en/book.oci8.php)
  * [ ] [ODBC](http://php.net/manual/en/book.uodbc.php)
  * [x] [PostgreSQL](http://php.net/manual/en/book.pgsql.php)
  * [x] [Readline](http://php.net/manual/en/book.readline.php)
  * [x] [Recode](http://php.net/manual/en/book.recode.php)
  * [x] [SNMP](http://php.net/manual/en/book.snmp.php)
  * [x] [XML-RPC](http://php.net/manual/en/book.xmlrpc.php)
* [ ] Documentation improvements

**Comment by petk** [comment]
Some extensions have been added, some are not relevant. Closing this.

**Comment by adaliszk** [comment]
I cannot use your awesome image at my current company because it doesn't support firebird :D in fact I have to create a huge ~500MB image from ubuntu/debian just to achive that. I would really like to have firebird support it in this lightweight image!

**Comment by petk** [comment]
Firebird currently isn't building properly without some patches on the Alpine linux. Yes, I'm aware that it would be good to have this and some other ones such as PDO for MS SQL server as well possible on Alpine.

Let me check what we can do with this one.
